In [1]:
import numpy as np

def point_in_triangle_3d(P, A, B, C, tol=1e-9):
    """
    Vérifie si le point P est dans le triangle défini par (A, B, C) en 3D.
    
    Paramètres :
    -----------
    P, A, B, C : array-like de taille 3
        Coordonnées des points (x, y, z).
    tol : float
        Tolérance numérique pour la coplanarité.
    
    Retour :
    --------
    True si P est dans le triangle, False sinon.
    """
    # Conversion en numpy
    P, A, B, C = map(np.array, (P, A, B, C))
    
    # Vecteurs
    v0 = C - A
    v1 = B - A
    v2 = P - A

    # Vérification coplanarité : (P-A) doit être orthogonal à n = (B-A) x (C-A)
    n = np.cross(B - A, C - A)
    if abs(np.dot(n, P - A)) > tol:
        return False  # P n'est pas dans le plan

    # Produits scalaires
    d00 = np.dot(v0, v0)
    d01 = np.dot(v0, v1)
    d11 = np.dot(v1, v1)
    d20 = np.dot(v2, v0)
    d21 = np.dot(v2, v1)

    # Déterminant
    denom = d00 * d11 - d01 * d01
    if abs(denom) < tol:
        return False  # Triangle dégénéré

    # Coordonnées barycentriques
    beta = (d11 * d20 - d01 * d21) / denom
    gamma = (d00 * d21 - d01 * d20) / denom
    alpha = 1 - beta - gamma

    # Test appartenance (dans [0,1] avec tolérance)
    return (alpha >= -tol) and (beta >= -tol) and (gamma >= -tol)

def triangle_area(A, B, C):
    """
    Calcule l'aire d'un triangle en 3D à partir des sommets A, B, C.
    
    Paramètres :
    -----------
    A, B, C : array-like (x, y, z)
    
    Retour :
    --------
    float : aire du triangle
    """
    A, B, C = map(np.array, (A, B, C))
    return 0.5 * np.linalg.norm(np.cross(B - A, C - A))

# Exemple d'utilisation
A = [0, 0, 0]
B = [0, 1, 0]
C = [1, 0, 0]
X1 = [0.51, 0.51, 0]
X2 = [0.5, 0.51, 0]
print(point_in_triangle_3d(X1, A, B, C))
print(point_in_triangle_3d(X2, A, B, C)) 
print(triangle_area(A, B, C))


False
False
0.5


In [2]:
import csv

coords = []
temps = []

with open("test_temperature_triangle.csv", newline="", encoding="utf-8-sig") as csvfile:
    spamreader = csv.reader(csvfile, delimiter=";")
    for i, row in enumerate(spamreader):
        values = list(map(float, row))  # Conversion en float
        if i < 3:
            coords.append(values)
        else:
            temps = values

# Transformation en numpy arrays
coords = np.array(coords)   # shape (3, n)
temps = np.array(temps)     # shape (n,)
n = coords.shape[1] 
print('n :',n)
print("Matrice des coordonnées (3 x n) :")
print(coords)

print("\nVecteur des températures :")
print(temps)

x = np.zeros((2, n))  

for i in range(n):
    A = coords[:, i]
    dist = np.linalg.norm(A - X1)  # distance euclidienne
    x[0, i] = dist
    x[1, i] = i                   # indice du point

print("Matrice distance+indices (2 x N) :")
print(x)

order = np.argsort(x[0, :])
x_sorted = x[:, order]

print("Distances triées + indices correspondants :")
print(x_sorted)

A = coords[:, int(x_sorted[1, 0])]
B = coords[:, int(x_sorted[1, 1])]
print("Point le plus proche :", A)
print("2ème point le plus proche :", B)


TA = temps[int(x_sorted[1, 0])]
TB = temps[int(x_sorted[1, 1])]
w = triangle_area(A,B,X1)
Tx = (TA+TB)/2

print('T(x) =',Tx)


    

n : 9
Matrice des coordonnées (3 x n) :
[[0. 1. 2. 0. 1. 2. 0. 1. 2.]
 [0. 0. 0. 1. 1. 1. 2. 2. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Vecteur des températures :
[10. 15. 10. 15. 50. 15. 10. 15. 10.]
Matrice distance+indices (2 x N) :
[[0.72124892 0.70724819 1.57486507 0.70724819 0.69296465 1.56850247
  1.57486507 1.56850247 2.10717821]
 [0.         1.         2.         3.         4.         5.
  6.         7.         8.        ]]
Distances triées + indices correspondants :
[[0.69296465 0.70724819 0.70724819 0.72124892 1.56850247 1.56850247
  1.57486507 1.57486507 2.10717821]
 [4.         1.         3.         0.         5.         7.
  2.         6.         8.        ]]
Point le plus proche : [1. 1. 0.]
2ème point le plus proche : [1. 0. 0.]
T(x) = 32.5


In [18]:
import pandas as pd
import pykrige

pd.read_csv('donnees_temperature.csv')
coords = pd.read_csv('donnees_temperature.csv')
print(coords[1])

KeyError: 1